import TopNav from "@/components/Nav/TopNav";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import { RecoilRoot } from "recoil";

export default function App({
  Component,
  // pageProps: { session, ...pageProps },
  pageProps,
}: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SessionProvider session={session}> */}
        <RecoilRoot>
          <Component {...pageProps} />
        </RecoilRoot>
      {/* </SessionProvider> */}
    </>
  );
}
