import TopNav from "@/components/Nav/TopNav";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";
import {
  Hydrate,
  QueryClient,
  QueryClientProvider,
  dehydrate,
} from "react-query";
import { useState } from "react";
import { ReactQueryDevtools } from 'react-query/devtools'

export default function App({
  Component,
  // pageProps: { session, ...pageProps },
  pageProps,
}: AppProps) {
  const [queryClient] = useState(()=> new QueryClient());
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SessionProvider session={session}> */}
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <RecoilRoot>
            <Component {...pageProps} />
          </RecoilRoot>
          <ReactQueryDevtools initialIsOpen={false} />
        </Hydrate>
      </QueryClientProvider>

      {/* </SessionProvider> */}
    </>
  );
}
